baseURL = "satRday_template"
title = "satRday"
theme = "hugo-universal-theme"
[params]
    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    about_us = "<p>satRdays are free/cheap accessible R conferences being organised by the community for the community.</p>"
    copyright = "Website developed using Hugo by the SatRdays team. It is under <a href=\"https://creativecommons.org/licenses/by/4.0/\" title=\"CC BY 4.0\">CC BY 4.0</a>."
